### ISSUE TITLE
depends on old turf

### ISSUE THREAD

**Issue by leiflinse-trivector** [dartclub/turf_pip#3]
turf_pip depends on turf 0.0.6 which if you use turf from github causes an issue where you have to use override to resolve it.

# How to reproduce
Depend on main branch of turf_dart
```
dependencies:
  turf:
    git:
      url: https://github.com/dartclub/turf_dart.git
      branch: main
```

Then run `dart pub get` which gives:

```
Resolving dependencies...
Because turf_pip 0.0.1+1 depends on turf ^0.0.6 and no versions of turf_pip match >0.0.1+1 <0.1.0, turf_pip ^0.0.1+1 requires turf from hosted.
So, because project_name depends on turf from git which depends on turf_pip ^0.0.1+1, version solving failed.
```

# How to work around
Add this to pubspec.yaml
```

dependency_overrides:
  # turf on github depends on turf_pip that depends on turf_0.0.6
  turf:
    git:
      url: https://github.com/dartclub/turf_dart.git
      branch: main
```

# Discussion
Not sure if this is intentional, or just result of work-in-progress.
